baseURL = "https://ebeno.org/"
defaultContentLanguage = "fr"
disableLanguages = []
googleAnalytics = ""
theme = "godocs-4"
title = "Ebeno"
[Languages.fr]
copyright = "Conçu avec l'aide de [Hugo](https://gohugo.io)"
languageCode = "fr-fr"
languageName = "Fr"
weight = 1
[Languages.fr.banner]
image = "park.png"
subtitle = "Le prix  général d'une essence ? Un fournisseur ? Des conseils ? "
title = "Référence pour <br>Ébénistes"
[Languages.fr.call_to_action]
content = "N'hésitez pas à faire des retours !"
enable = false
image = "images/cta-illustration.jpg"
title = "Vous avez une question ou une demande ?"
[Languages.fr.call_to_action.button]
enable = "true"
label = "Ecrire une demande !"
link = "contact/"
[Languages.fr.feedback]
content = "Vos commentaires nous aident à améliorer la plateforme."
negative_placeholder = "Que pouvons-nous améliorer cette page ?"
positive_placeholder = "Qu'avez-vous aimé sur cette page ?"
title = "Avez-vous trouvé ces informations pertinentes ?"
[[Languages.fr.menu.footer]]
name = "L'équipe"
url = "/about/"
weight = 1
[[Languages.fr.menu.footer]]
name = "Contact"
url = "/contact/"
weight = 2
[markup.goldmark.renderer]
unsafe = true
[outputs]
home = ["HTML", "JSON"]
[params]
author = "Jean Doukhan"
contact_form_action = "https://formspree.io/f/xqkjgjyb"
description = "Site de référence pour ébénistes"
feedback_form_action = "https://formspree.io/f/xlevovpl"
[params.logo]
docs_logo = "nom_seul2.png"
favicon = "logo.png"
logo_icon = ""
main = "logo.png"
main_site_link = "https://ebeno.org"
site_logo = "logo.png"
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/search/auto-complete.css"
[[params.plugins.css]]
link = "plugins/featherlight/featherlight.min.css"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
attributes = "crossorigin='anonymous' defer='defer' data-search-pseudo-elements"
link = "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/js/all.min.js"
[[params.plugins.js]]
link = "plugins/masonry/masonry.min.js"
[[params.plugins.js]]
link = "plugins/featherlight/featherlight.min.js"
[[params.plugins.js]]
link = "plugins/clipboard/clipboard.min.js"
[[params.plugins.js]]
link = "plugins/search/auto-complete.js"
[[params.plugins.js]]
link = "plugins/search/search.js"
[[params.plugins.js]]
link = "plugins/search/lunr.min.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search-page.js"
[params.preloader]
enable = false
preloader = ""
[params.variables]
black = "#000"
body_color = "#fff"
border_color = "#E2E2E2"
icon_font = "Font Awesome 5 Free"
light = "#FBFBFB"
primary_color = "#bf9000"
primary_font = "Montserrat:wght@300;400;500;600;700;800"
primary_font_type = "sans-serif"
secondary_font = ""
secondary_font_type = ""
text_color = "#333"
text_color_dark = "#222"
text_color_light = "#999"
white = "#fff"

        <div data-netlify-identity-button>Se connecter</div>
[[params.nav_button]]
label = "Connexion"
link = "admin/"
style = "outline"
[[params.nav_button]]
label = "L'équipe"
link = "about/"
style = "outline"
[[params.nav_button]]
label = "contact"
link = "contact/"
style = "solid"

[[params.social]]
icon = "fas fa-address-card"
link = "https://jean.doukhan.pro"
title = "Qui suis-je ?"
[[params.social]]
icon = "fab fa-linkedin"
link = "https://www.linkedin.com/in/jean-doukhan/"
title = "Mon LinkedIn"
