backend:
  name: git-gateway
  branch: main
media_folder: "static/images" # Folder where user uploaded files should go
public_folder: "images"
locale: 'fr'
site_url: https://www.ebeno.org
logo_url: /static/logo.png
collections:
  - name: "Bois" # Used in routes, e.g., /admin/collections/post
    label: "Bois" # Used in the UI
    folder: "content/Bois" # The path to the folder where the documents are stored
    path: "{{slug}}/index"
    media_folder: "" # Save images in the post's own folder instead of the static folder
    public_folder: ""
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in front matter
      - {label: "Page Brouillon (non public)", name: "draft", widget: "boolean", required: false, default: true, hint: "Désactiver l'option pour poster publiquement la page."}
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Date de publication", name: "date", widget: "datetime" }
      - { label: "Contenu", name: "body", widget: "markdown" }


  - name: "Fournisseurs" # Used in routes, e.g., /admin/collections/post
    label: "Fournisseurs" # Used in the UI
    folder: "content/Fournisseurs" # The path to the folder where the documents are stored
    path: "{{slug}}/index"
    media_folder: "" # Save images in the post's own folder instead of the static folder
    public_folder: ""
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in front matter
      - {label: "Page Brouillon (non public)", name: "draft", widget: "boolean", required: false, default: true, hint: "Désactiver l'option pour poster publiquement la page."}
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Date de publication", name: "date", widget: "datetime" }
      - { label: "Contenu", name: "body", widget: "markdown" }


  - name: "Techniques" # Used in routes, e.g., /admin/collections/post
    label: "Techniques et Conseils" # Used in the UI
    folder: "content/Techniques" # The path to the folder where the documents are stored
    path: "{{slug}}/index"
    media_folder: "" # Save images in the post's own folder instead of the static folder
    public_folder: ""
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in front matter
      - {label: "Page Brouillon (non public)", name: "draft", widget: "boolean", required: false, default: true, hint: "Désactiver l'option pour poster publiquement la page."}
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Date de publication", name: "date", widget: "datetime" }
      - { label: "Contenu", name: "body", widget: "markdown" }
 